default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: moviedb_development
  username: <%= ENV['DEV_USER'] %>
  password: <%= ENV['DEV_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: moviedb_test
  username: <%= ENV['TEST_USER'] %>
  password: <%= ENV['TEST_PASSWORD'] %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: <%= ENV['MOVIEDB_DATABASE_URL'] %>
  username: <%= ENV['MOVIEDB_DATABASE_DB'] %>
  password: <%= ENV['MOVIEDB_DATABASE_PASSWORD'] %>
